### ISSUE TITLE
General code style inconsistency issues

### ISSUE THREAD

**Issue by olivierobert** [liamstevens111/django-google-search-data-viewer#12]
## Issue

While indentation is not many issues in the Python files (otherwise the code would fail 😉 ), there are still some. Not sure what happened with the braces 🙈 

https://github.com/liamstevens111/google-search-data-viewer/blob/8ac9363bf1cffbfc063a5b9a05ebf1f8b6c9d04e/googlesearchdataviewer/apps/users/admin.py#L23-L29

The templates files for the `users` app need some formatting 🧡 

https://github.com/liamstevens111/google-search-data-viewer/blob/8ac9363bf1cffbfc063a5b9a05ebf1f8b6c9d04e/googlesearchdataviewer/apps/users/templates/users/login.html#L12-L24

It would be neater as the following:

```html
  <form method="post">
    {% csrf_token %}
    <div class="form-group col-md-4 mb-0 mx-auto mt-2">
      {{ form.username|as_crispy_field }}
    </div>
    <div class="form-group col-md-4 mb-0 mx-auto mt-2">
      {{ form.password|as_crispy_field }}
    </div>
    <div class="col-md-4 mb-0 mx-auto mt-2">
      <button class="btn btn-primary" type="submit">Sign in</button>
     </div>
  </form>
```

[This CSS file](https://github.com/liamstevens111/google-search-data-viewer/blob/main/googlesearchdataviewer/static/css/style.css) is empty and should be deleted.

## Expected

The code should be formatted consistently throughout the codebase.

**Comment by liamstevens111** [comment]
I am not sure what happened with those braces either ::sob: :laughing:  Fixed.

I think the issues with the formatting/indentation in the HTML template occurred when I was fighting with my VS Code auto-formatter which was having issues when it contained Django template tags (it was splitting them up placing them at the end of the line). Should be all good now.

Regarding the empty CSS file; I originally planned to incorporate some custom CSS with a SASS pre-processor rather than purely bootstrap but didn't get round to doing it. I have deleted it for now.

The pull request can be found [here](https://github.com/liamstevens111/google-search-data-viewer/pull/16)
